# Generated by Django 5.0.1 on 2024-02-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
